# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_01_IP      = "192.168.56.30"
NODE_02_IP      = "192.168.56.31"

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.box_version = "1.0.3"

  boxes = [
    { :name => "node-01", :ip => NODE_01_IP, :cpus => 1, :memory => 2048 },
    { :name => "node-02", :ip => NODE_02_IP, :cpus => 1, :memory => 2048 },
  ]

  boxes.each do |opts|
    config.vm.define opts[:name] do |box|
      box.vm.hostname = opts[:name]
      box.vm.network :private_network, ip: opts[:ip]
 
      box.vm.provider "virtualbox" do |vb|
        vb.cpus = opts[:cpus]
        vb.memory = opts[:memory]
      end
      box.vm.provision "install",type: "shell", path:"./install.sh"
      box.vm.provision "ssh", type: "shell", privileged: false, path:"./config-ssh.sh"
    end
  end
end
